Repository ibuttimer/in-for-a-penny, pull requests merged in 2023-01, with the labels that each got.

#8 idea2
  doc/planning/planning.md
Labels: documentation, kanban

#13 doc: Add meeting minutes
  .pylintrc
  .sample-env
  Procfile
  README.md
  base/__init__.py
  base/admin.py
  base/apps.py
  base/constants.py
  base/context_processors.py
  base/migrations/__init__.py
  base/models.py
  base/tests.py
  base/urls.py
  base/views.py
  doc/planning/meeting-log.md
  doc/planning/planning.md
  in_for_a_penny/__init__.py
  in_for_a_penny/asgi.py
  in_for_a_penny/constants.py
  in_for_a_penny/settings.py
  in_for_a_penny/urls.py
  in_for_a_penny/wsgi.py
  manage.py
  requirements-dev.txt
  requirements.txt
  robots.txt
  runtime.txt
  setup.cfg
  sitemap.xml
  static/css/styles.css
  static/img/.keep
  static/js/script.js
  staticfiles/.keep
  templates/base.html
  templates/base/landing.html
Labels: documentation

#24 doc: Add meeting minutes
  .gitignore
  README.md
  doc/planning/meeting-log.md
Labels: documentation

#30 feat: Activate login urls #5
  in_for_a_penny/constants.py
  in_for_a_penny/settings.py
  in_for_a_penny/urls.py
Labels: kanban

#33 feat: Added login/logout/register to navbar #5 #6 #7
  templates/base.html
Labels: kanban

#52 maint: Change app name #49
  in_for_a_penny/constants.py
  templates/base.html
Labels: kanban

#54 feat: Add convert to main menu
  templates/base.html
  templates/base/convert.html
Labels: kanban

#55 fix: MIME type error on deployed site
  templates/base.html
Labels: kanban
